from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '184783e648ef'
down_revision = '7b537a3c7804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('payment')
    # op.drop_table('menuorder')
    # op.drop_table('menuorderitems')
    # op.drop_table('taxes')
    op.create_foreign_key(None, 'menucat', 'menumaincat', ['main_cat_id'], ['id'])
    op.create_foreign_key(None, 'menuitem', 'menucat', ['cat_id'], ['id'])
    op.create_foreign_key(None, 'userpromo', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'userpromo', 'promocode', ['promo_code'], ['promo_code'])
    op.create_foreign_key(None, 'users_address', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_address', type_='foreignkey')
    op.drop_constraint(None, 'userpromo', type_='foreignkey')
    op.drop_constraint(None, 'userpromo', type_='foreignkey')
    op.drop_constraint(None, 'menuitem', type_='foreignkey')
    op.drop_constraint(None, 'menucat', type_='foreignkey')
    op.create_table('taxes',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tax_name', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('tax_per', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.create_table('menuorderitems',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('menu_item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('menu_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('choice', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.create_table('menuorder',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('payment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('address_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('promo_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('special_note', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ratings', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    op.create_table('payment',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('payment_type', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('transaction_id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('date_time_of_payment', sa.DATE(), nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'MyISAM'
    )
    # ### end Alembic commands ###
