"""empty message

Revision ID: 300237664105
Revises: 8a946646ece8
Create Date: 2017-07-22 21:37:10.231000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300237664105'
down_revision = '8a946646ece8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'menucat', 'menumaincat', ['main_cat_id'], ['id'])
    op.create_foreign_key(None, 'menuitem', 'menucat', ['cat_id'], ['id'])
    op.create_foreign_key(None, 'userpromo', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'userpromo', 'promocode', ['promo_code'], ['promo_code'])
    op.create_foreign_key(None, 'users_address', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_address', type_='foreignkey')
    op.drop_constraint(None, 'userpromo', type_='foreignkey')
    op.drop_constraint(None, 'userpromo', type_='foreignkey')
    op.drop_constraint(None, 'menuitem', type_='foreignkey')
    op.drop_constraint(None, 'menucat', type_='foreignkey')
    # ### end Alembic commands ###
