"""empty message

Revision ID: 8a946646ece8
Revises: 
Create Date: 2017-07-22 21:35:55.142000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a946646ece8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menumaincat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocode',
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.String(length=10), nullable=False),
    sa.Column('promo_discount_per', sa.Integer(), nullable=False),
    sa.Column('promo_validity', sa.Date(), nullable=False),
    sa.Column('promo_wallet', sa.Boolean(), nullable=False),
    sa.Column('promo_user', sa.Boolean(), nullable=False),
    sa.Column('promo_description', sa.String(length=100), nullable=False),
    sa.Column('promo_url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('promo_id'),
    sa.UniqueConstraint('promo_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=20), nullable=True),
    sa.Column('lname', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('refcode', sa.String(length=8), nullable=True),
    sa.Column('register_ref', sa.String(length=8), nullable=True),
    sa.Column('register_ref_no', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('wallet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('refcode')
    )
    op.create_table('menucat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=50), nullable=False),
    sa.Column('main_cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_cat_id'], ['menumaincat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userpromo',
    sa.Column('userpromo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('promo_code', sa.String(length=8), nullable=True),
    sa.Column('userpromo_validity', sa.Date(), nullable=False),
    sa.Column('userpromo_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['promo_code'], ['promocode.promo_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userpromo_id')
    )
    op.create_table('users_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('delivery_area', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('instructions', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menuitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('full_price', sa.Integer(), nullable=False),
    sa.Column('half_price', sa.Integer(), nullable=True),
    sa.Column('choice', sa.Boolean(), nullable=True),
    sa.Column('choice_one', sa.String(length=80), nullable=True),
    sa.Column('choice_two', sa.String(length=80), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['menucat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menuitem')
    op.drop_table('users_address')
    op.drop_table('userpromo')
    op.drop_table('menucat')
    op.drop_table('users')
    op.drop_table('promocode')
    op.drop_table('menumaincat')
    # ### end Alembic commands ###
